# Generated by Django 3.0.3 on 2020-03-02 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0002_remove_detail_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='Image',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
