# Generated by Django 3.0.3 on 2020-02-26 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeee',
            name='mobile',
            field=models.CharField(max_length=10),
        ),
    ]
